name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "294f9d1b5b078f8d4414cb51cc33aa6d7ae4d8e20c64ac6c2b14ed82b5195506"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
