name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af3003be4ef5ad2a3526c3cf96ec380ddd87571acc948a70972b666ccf594e4a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
