name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4cdb70fca876c30f83cfc1b9cb1fcc61ffb0eca7f8c8c139bf03ceee9ea72b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
