name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242e5e1ce798274eb7de3963170e654d8a5fb70187d7d577c20f75783959cba9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
