name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f45c6c98d0075fbdedcfff2064f6d28463b35c8203278499cb47d6ca31a086e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
