name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3326b3046c682611e88d0d831879a9064650e380bbfa32c5367f8f87480c35e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
