name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeecc8c232f477b200949540a96e38ee01bde53a212958396129ddb9931c32ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
