name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9c9df04efc78c65b168026a83354d12f28e189859662611ab7be24debe5d44e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
