name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc0f1e59df64e4ecb97900fdf405e68229efd58ece54b58f87e49f5036e0a539"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"

[options]
no-internal-hashes = true
