name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7755ec8135a1c842b7d95031755bbec09c3279028c0675c25bb5a430007ccd71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
