name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b46cc0171d1c29bdd6ee3a6fa02e495209309e53cad5f4c07d874e12bcb4558"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"

[options]
no-internal-hashes = true
