name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62debde09277ad0322fab5aacf3ed6c93d4ca3ec1a1bf123606a8d4e36177fa9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
