name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a413df343aa2c800f99933b0732d04a6a84296d7ab5e719e0e6a4bb2128982c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
