name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7b61db2c8c11e62165961be5236f76671bfed63ca86c7442f3d8b11944f9ffd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
