name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b185f3b925cf51c7163bf0624122c4ab76c9c2d4d73e92647a6be4e4fa153bc3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
