name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "124990015ebddd0c64cb8f0a68831880fcaa91b9399e3dd5b2dce2d24b73fa0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
