name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8605d0f26c2480da44023ecaef23887e517e71794751c53547f20f6d494c1dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
