name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81a3cc58826846449fdfafbadd09601d730a2cd3e388bdc9d1621a2bacf3795d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"

[options]
no-internal-hashes = true
