name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70ddce0d2b448e8464ff3b717e6aa9f3322691a86bae3dfbd78b4af313fa6986"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
