name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62d79c6a9d5e14fcf5ab7b6c804d1f578743d03860a7ce4264ee1a84278b98af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
