name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b109c9cbbdbfe06d17f46b976374ab4700fa73a571289c71225232b694382f05"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"

[options]
no-internal-hashes = true
