name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aac01e96ae71104abe43ffc69fdf1f5fa8535b0f281fb403d279111a4588bec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
