name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4683f31630e4c58630c152e7861c152ff6f5ee10286c4498e9ba4d06d23e9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
