name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "091853d11a7fdb0b48f6341da808b37d68fb0a28199965af5ca27bcf458a6671"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
