name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ef24a6523bfafbe0aafad6d613252393e7b5fdc71c0ff37fb439ef22aff98a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
