name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93fb26f883251025ba2c227621be288a57a303b6ae4cdca8226690afe1454d91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
