name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2074d3accd1ce2381c6fc8f85f120880ef992cbd77438fbd43cc851472b05269"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
