name = "JSPCD 6 Packwiz"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9354edd90460fab8525f0e41d6dc4dac167aefb6eb84fb7d293d8ef5e836ff62"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
