name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a0e4257485362a280779e85397fb74877bf1ffbcf4d35ad9e4f2c0627f4fe72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
