name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c6d0a7adc4cda758ff9c4c0b4344dd4bbdce91fb3044bbf536fd7fa0faeab58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
