name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb61cca3460b0b94bc8089e1b585d17652d1e8fc82ef3b2f9a60e576447342d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
