name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a1575e5ab729fa9b4684c0ddfd8c0827cce32bcbc0afebafae3b402d5caf88a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
