name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "814272bef0a1d1356ee1b67a8f47dd482d13b541eadf531c0c4ccfbc8dbca0c4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
