name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1441a1608f5406a22438464ae773887a02eebc7e9aebc6cc5fd24cf68aa7259"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
