name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2458336598ee05e359208a310fa30e72571b29dc6849feb69dd55a47b0cf9055"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
