name = "JSPCD 6 Packwiz"
author = "Codion"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d7cc2635430e1d653de77a202127fc05240cd277fc447e4c04e1c190890f9da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
